name: Unity WebGL Build 😎

# only run when pushed to master or main branches
on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    name: Build WebGL
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository 🛒
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: 'true'

      # Cache
      - name: Cache 💾
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-WebGL-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-WebGL-
            Library-

      # Build
      - name: Build project 🔨
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          versioning: Semantic
          targetPlatform: WebGL
          unityVersion: auto
          
      # Deploy    
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/WebGL/WebGL # The folder the action should deploy.
          single-commit: true
          
      # Archive artifacts    
      - uses: actions/upload-artifact@v4
        with:
          name: Build-WebGL
          path: build/WebGL

    